# 🌟 CPP Module 04

과제를 하면서 공부한 내용들(을 엄청 대충 정리함)

## 🌸 Exception

예외란 정상적인 실행을 방해하는 조건이나 상태를 의미한다.

예외를 점검하는 전통적인 방법은 if문인데 (반환값에 조건을 걸어 검사한다든지, 등) 점검해야 할 예외가 많아지면 다량의 if문이 필요하게 되고 보기가 좋지 않다. 는 문제와 , 예외처리와 실제 코드가 한데 엉켜 있게 되어서 코드의 핵심 동작을 파악하기가 어렵다는 문제가 있다.

따라서 C++에서는 언어 차원에서 예외 처리 문법을 제공하고, 예외 처리를 위해서 3가지 키워드를 제공한다.

- `try` : 예외가 발생할 가능성이 있는 코드를 감싼다. 예외가 발생했을 때 `throw` 로 예외를 **던져**준다.
- `throw` : 예외가 발생하면 예외를 던져서 `catch` 키워드로 이동한다. `throw()` 괄호 안에는 예외를 설명하는 값이나 객체가 들어간다.
- `catch` : 예외를 받아서 처리하는 핸들러. 받고자 하는 예외를 명시해줘야 한다. 이 블록 안에 예외처리 방식을 정의한다.

try 블록 안에서 예외가 발생하지 않으면 그 아래에 있던 catch 블록은 무시된다.

```cpp
try
{
  int a;
  ...
  throw(a)
}
catch (int a)
{
  std::cout << "에러 났어!!" << std::endl;
}
```

원칙적으로 throw는 try 블록에 있어야 하지만, 외부 함수에서도 throw를 할 수 있다. 이 경우에는 throw 예외를 함수를 호출한 쪽에서 처리한다.

```cpp
void error (void)
{
  ...
  if (...)
    throw(1);
}

int main(void)
{
  ...
  try
  {
    error();
  }
  catch (int a)
  {
    std::cout << "에러 났어!!" << std::endl;
    return;
  }
}
```

이런 식으로 error 함수에서 에러가 던져지면, **error 함수의 호출 스택을 정리하고** error 함수를 호출했던 try-catch 문으로 돌아와 catch 블록으로 들어간다.